services:
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=aklisch_dev
    volumes:
      - ./temp/mysql_data:/var/lib/mysql
  admin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
    - MYSQL_ROOT_PASSWORD=pass
    - MYSQL_PASSWORD=test